env:
  es6: true
  browser: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
  ecmaVersion: 2018
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
globals:
  require: true
  module: true
